### ISSUE TITLE
Relicence?

### ISSUE THREAD

**Issue by mario** [nextcloud/ownCloud-Account-Importer#4]
Can you relicence this to GPL3+? AGPL is not useful for non-server software, and I'm unsure what implications it has if you mix GPL3+ and AGPL (though it should work, but no an expert!).

**Comment by David-Development** [comment]
Okay, it's under GPL3 now. (https://github.com/nextcloud/ownCloud-Account-Importer/commit/2dc4d25e279be787ac24c3df9183c2e97209a027)
